proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  docker:
      internal-networking: true
  specs:
  - id: testapp
    display-name: Test App
    container-image: testapp
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log
